apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: webserver
  labels:
    environment: dev
    run: nginx-pod-with-secret
    tier: frontend
  name: nginx-pod-with-secret
  namespace: default
spec:
  containers:
    - name: nginx-pod
      image: nginx:latest
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-opaque-type-from-env-file
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-opaque-type-from-env-file
              key: password
        - name: ROLE
          valueFrom:
            secretKeyRef:
              name: secret-opaque-type-from-env-file
              key: role
