apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: webserver
  labels:
    environment: dev
    run: nginx-pod-with-mounted-secret
    tier: frontend
  name: nginx-pod-with-mounted-secret
  namespace: default
spec:
  containers:
    - name: nginx-pod
      image: nginx:latest
      volumeMounts:
        - name: mounted-secret-volume
          mountPath: /etc/conf
          readOnly: true
  volumes:
    - name: mounted-secret-volume
      secret:
        secretName: mounted-secret
