# three node cluster configuration with one control-plane and two workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-samples
nodes:
  - role: control-plane
  - role: worker
  - role: worker
