apiVersion: v1
kind: Pod
metadata:
  labels:
    environment: dev
    run: nginx-pod
    tier: frontend
  name: nginx-pod
  namespace: default
spec:
  containers:
    - image: nginx:latest
      name: nginx-pod
