apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: webserver
  labels:
    environment: dev
    run: nginx-pod
    tier: frontend
  name: nginx-pod
  namespace: default
spec:
  containers:
    - name: nginx-pod
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
