apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  labels:
    app: webserver-deploy
spec:
  selector:
    app: webserver-deploy
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      nodePort: 31001
