apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: test
  labels:
    environment: dev
    tier: testing
  name: multi-container-with-empty-dir-volumes-sharing-pod
  namespace: default
spec:
  restartPolicy: OnFailure
  containers:
    - name: httpd-container
      image: httpd:latest
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: shared
          mountPath: /var/shared
    - name: busybox-container
      image: busybox:latest
      command: ["sleep"]
      args: ["180"]
      volumeMounts:
        - name: shared
          mountPath: /var/shared
  volumes:
    - name: shared
      emptyDir: {}
