apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver-rs-equality-based-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
      environment: dev
  template:
    metadata:
      labels:
        app: webserver
        environment: dev
    spec:
      containers:
        - name: webserver
          image: httpd:2.4
          imagePullPolicy: IfNotPresent
          # the httpd image is pulled only if it is not already present locally
          ports:
            - containerPort: 80
              protocol: TCP
