apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver-rs-set-based-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
    matchExpressions:
      - key: environment
        operator: In
        values:
          - dev
          - test
  template:
    metadata:
      labels:
        app: webserver
        environment: dev
    spec:
      containers:
        - name: webserver
          image: httpd:latest
          imagePullPolicy: IfNotPresent
          # the httpd image is pulled only if it is not already present locally
          ports:
            - containerPort: 80
              protocol: TCP
