apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: webserver
  labels:
    environment: dev
    run: nginx-pod-with-mounted-configmap
    tier: frontend
  name: nginx-pod-with-mounted-configmap
  namespace: default
spec:
  volumes:
    - name: mounted-configmap-volume
      configMap:
        name: mounted-configmap
  containers:
    - name: nginx-pod
      image: nginx:1.27
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mounted-configmap-volume
          mountPath: /etc/conf
          readOnly: true
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
