apiVersion: v1
kind: Service
metadata:
  name: lorem-svc
  labels:
    app: lorem
spec:
  externalIPs: 
    ## replace the following placeholder with the private IP address of interest
    - 'private_ip_address'
  selector:
    app: lorem
  type: NodePort
  ports:
    - port: 8080
      # nodePort: 31001
      protocol: TCP
      targetPort: 80
