apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: test
  labels:
    environment: dev
    tier: testing
  name: multi-container-with-init-pod
  namespace: default
spec:
  initContainers:
    - name: custom-init-container
      image: busybox:latest
      command: ["sleep", "15"]
  restartPolicy: OnFailure
  containers:
    - name: httpd-container
      image: httpd:latest
      ports:
        - containerPort: 80
          protocol: TCP
    - name: busybox-container
      image: busybox:latest
      command: ["sleep"]
      args: ["60"]
