apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: test
  labels:
    environment: dev
    tier: testing
  name: multi-container-with-init-pod
  namespace: default
spec:
  initContainers:
    - name: custom-init-container
      image: busybox:latest
      command: ["sleep", "15"]
  restartPolicy: OnFailure
  containers:
    - name: httpd-container
      image: httpd:2.4
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
    - name: busybox-container
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sleep"]
      args: ["60"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "200m"
