apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
      environment: dev
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webserver
        environment: dev
    spec:
      containers:
        - name: webserver
          image: httpd:2.4
          imagePullPolicy: IfNotPresent
          ## the httpd image is pulled only if it is not already exist on the node
          ports:
            - containerPort: 80
              protocol: TCP
          ## resource limit settings
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
              ## two hundred thousandths of a CPU core, 20%
